### ISSUE TITLE
Where is Mana Reader?

### ISSUE THREAD

**Issue by Schwarin** [Zombiebear99/manavisualizer#2]
Informations:
Forge: 47.2.19
Java: 17

Resume:

I can't find Mana Reader and the mod is installed correctly.

It appears in the mods tab, it appears to be installed, however, I can't find it anywhere. Are you still implementing it? I was in doubt and decided to report it.

I apologize if I did something wrong, or if I reported it unnecessarily.

If you will need something about this, contact me.

NOTE: I'm using Google Translate, as I don't know much English, so if there are any errors, I'm sorry.

![Screenshot_11](https://github.com/Zombiebear99/manavisualizer/assets/106997804/81b3092f-8b1a-4c39-8dc0-aa1f294c93e2)
![image](https://github.com/Zombiebear99/manavisualizer/assets/106997804/ffd0c567-4fcc-4642-8dc8-b47ec7cf1398)

**Comment by Zombiebear99** [comment]
can you send logs.

**Comment by Schwarin** [comment]
Yes, I can.

[latest.log](https://github.com/Zombiebear99/manavisualizer/files/13898321/latest.log)

**Comment by Zombiebear99** [comment]
looks like this issue is on your end as i cant seem to find any error in the log.
also this the first issue for this version.

**Comment by Schwarin** [comment]
Oh, ok, I'll do some tests to see if I can figure out the problem.
Thanks for trying to help me.
I'll try to talk to you if I can find the error (if it's relevant to you)
NOTE: If I find the problem, and you are interested, I can send it to you via the CurseForge website.

**Comment by Schwarin** [comment]
I discovered with some tests that it is working "normally", as I can't find it in the JEI and in the Creative tab. However, I can make it at a crafting table or obtain it via /give.
Sorry for not testing properly.
